(load-extension "target/release/libjson_parser.so" "scm_init_json_parser_module")
(use-modules (json parser))
(display (read-string "null"))
(display "\n")
(display (read-string "false"))
(display "\n")
(display (read-string "true"))
(display "\n")
(display (read-string "10"))
(display "\n")
(display (read-string "-10"))
(display "\n")
(display (read-string "3.4"))
(display "\n")
(display (read-string "18446744073709551610"))
(display "\n")
(display (read-string "\"kuku kiki กา\""))
(display "\n")
(display (read-string "[1, \"xxx\", {\"a\":30}]"))
(display "\n")
(display "@@@\n")



